# Generated by Django 6.0.6 on 2026-06-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date'], 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'verbose_name': 'Тип тренировки', 'verbose_name_plural': 'Типы тренировок'},
        ),
    ]
