# Generated by Django 6.0.6 on 2026-06-18 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'verbose_name': 'Журнал упражнения', 'verbose_name_plural': 'Журналы упражнений'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-date'], 'verbose_name': 'Прогресс пользователя', 'verbose_name_plural': 'Прогресс пользователей'},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date'], 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'verbose_name': 'Тип тренировки', 'verbose_name_plural': 'Типы тренировок'},
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_name',
            field=models.CharField(max_length=100, verbose_name='Название упражнения'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='reps',
            field=models.PositiveIntegerField(verbose_name='Повторения'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='sets',
            field=models.PositiveIntegerField(verbose_name='Подходы'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='weight',
            field=models.FloatField(verbose_name='Рабочий вес (кг)'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workout', verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='body_weight',
            field=models.FloatField(verbose_name='Масса тела (кг)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='date',
            field=models.DateField(verbose_name='Дата замера'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.FloatField(verbose_name='Сожженные калории'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.workouttype', verbose_name='Тип активности'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название активности'),
        ),
    ]
