# Generated by Django 6.0.6 on 2026-06-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-date'], 'verbose_name': 'Прогресс пользователя', 'verbose_name_plural': 'Прогресс пользователей'},
        ),
    ]
